# Dependabot configuration for automated dependency updates
# This helps keep dependencies secure and up-to-date
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 10
    groups:
      # Group development dependencies
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      # Group production dependencies by type
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
    # Labels for pull requests
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Monitor apps/docs
  - package-ecosystem: "npm"
    directory: "/apps/docs"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docs"
    commit-message:
      prefix: "chore(deps)"

  # Monitor apps/showcase
  - package-ecosystem: "npm"
    directory: "/apps/showcase"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "showcase"
    commit-message:
      prefix: "chore(deps)"

  # Monitor packages/registry
  - package-ecosystem: "npm"
    directory: "/packages/registry"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "registry"
    commit-message:
      prefix: "chore(deps)"

  # Monitor packages/cli
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "cli"
    commit-message:
      prefix: "chore(deps)"

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
