name: 🐛 Bug Report
description: Report a bug or unexpected behavior in React Native USMDS
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: When I click the button...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Install component using '...'
        2. Use the component with props '...'
        3. Observe the error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The button should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, the button...
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Component(s) Affected
      description: Which component(s) are affected by this bug?
      placeholder: "e.g., Button, Alert, Card"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) does this affect?
      multiple: true
      options:
        - iOS
        - Android
        - Web
        - All platforms
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - React Native USMDS version:
        - React Native version:
        - Expo version (if applicable):
        - Node version:
        - OS:
        - Device/Emulator:
      render: markdown
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      render: tsx
      placeholder: |
        import { Button } from '@blen/usmds'

        export default function MyComponent() {
          return <Button>Click me</Button>
        }

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: Drag and drop images or paste URLs here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (e.g., workarounds, related issues)
      placeholder: This seems to be related to...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](https://github.com/blencorp/react-native-usmds/blob/main/CONTRIBUTING.md)
      options:
        - label: I have read and agree to follow the Contributing Guidelines
          required: true
