// This file is auto-generated. Do not edit manually.
// Generated by: packages/cli/scripts/build-registry.ts
// Run 'yarn build:registry' to regenerate

export const ALL_COMPONENTS = [
  'Alert',
  'Avatar',
  'Badge',
  'Banner',
  'Biometricsignin',
  'Button',
  'Buttongroup',
  'Card',
  'Checkbox',
  'Checkboxtile',
  'Collapsible',
  'Dialog',
  'Icon',
  'Link',
  'Pagination',
  'Progress',
  'Radiobutton',
  'Radiotile',
  'Snackbar',
  'Stepindicator',
  'Tag',
  'Text',
  'Textarea',
  'Textinput',
  'Toggle'
];

interface ComponentMetadata {
  name: string;
  dependencies?: string[];
  internalDependencies?: string[];
}

export const COMPONENT_METADATA: Record<string, ComponentMetadata> = {
  Alert: {
    name: 'Alert',
    internalDependencies: ['icon', 'text']
  },
  Avatar: {
    name: 'Avatar',
    dependencies: ['@rn-primitives/avatar']
  },
  Badge: {
    name: 'Badge',
    dependencies: ['@rn-primitives/slot'],
    internalDependencies: ['text']
  },
  Banner: {
    name: 'Banner'
  },
  Biometricsignin: {
    name: 'Biometricsignin',
    dependencies: ['@rn-primitives/checkbox'],
    internalDependencies: ['icon']
  },
  Button: {
    name: 'Button',
    internalDependencies: ['text']
  },
  Buttongroup: {
    name: 'Buttongroup'
  },
  Card: {
    name: 'Card',
    internalDependencies: ['text']
  },
  Checkbox: {
    name: 'Checkbox',
    dependencies: ['@rn-primitives/checkbox'],
    internalDependencies: ['icon']
  },
  Checkboxtile: {
    name: 'Checkboxtile',
    dependencies: ['@rn-primitives/checkbox'],
    internalDependencies: ['icon']
  },
  Collapsible: {
    name: 'Collapsible',
    dependencies: ['@rn-primitives/collapsible']
  },
  Dialog: {
    name: 'Dialog',
    dependencies: ['@rn-primitives/dialog'],
    internalDependencies: ['icon']
  },
  Icon: {
    name: 'Icon'
  },
  Link: {
    name: 'Link',
    internalDependencies: ['icon']
  },
  Pagination: {
    name: 'Pagination',
    internalDependencies: ['icon']
  },
  Progress: {
    name: 'Progress',
    dependencies: ['@rn-primitives/progress']
  },
  Radiobutton: {
    name: 'Radiobutton',
    dependencies: ['@rn-primitives/radio-group']
  },
  Radiotile: {
    name: 'Radiotile',
    dependencies: ['@rn-primitives/radio-group']
  },
  Snackbar: {
    name: 'Snackbar',
    internalDependencies: ['icon']
  },
  Stepindicator: {
    name: 'Stepindicator'
  },
  Tag: {
    name: 'Tag'
  },
  Text: {
    name: 'Text',
    dependencies: ['@rn-primitives/slot']
  },
  Textarea: {
    name: 'Textarea'
  },
  Textinput: {
    name: 'Textinput'
  },
  Toggle: {
    name: 'Toggle',
    dependencies: ['@rn-primitives/toggle'],
    internalDependencies: ['icon', 'text']
  }
};

export const COMPONENT_TEMPLATES: Record<string, string> = {
  Alert: `import { Icon } from '@/components/ui/icon';
import { Text, TextClassContext } from '@/components/ui/text';
import { cn } from '@/lib/utils';
import type { LucideIcon } from 'lucide-react-native';
import * as React from 'react';
import { View, type ViewProps } from 'react-native';

function Alert({
  className,
  variant,
  children,
  icon,
  iconClassName,
  ...props
}: ViewProps &
  React.RefAttributes<View> & {
    icon: LucideIcon;
    variant?: 'default' | 'destructive';
    iconClassName?: string;
  }) {
  return (
    <TextClassContext.Provider value={cn('text-sm text-foreground', variant === 'destructive' && 'text-destructive', className)}>
      <View role='alert' className={cn('bg-card border-border relative w-full rounded-lg border px-4 pb-2 pt-3.5', className)} {...props}>
        <View className='absolute left-3.5 top-3'>
          <Icon as={icon} className={cn('size-4', variant === 'destructive' && 'text-destructive', iconClassName)} />
        </View>
        {children}
      </View>
    </TextClassContext.Provider>
  );
}

function AlertTitle({ className, ...props }: React.ComponentProps<typeof Text> & React.RefAttributes<Text>) {
  return <Text className={cn('mb-1 ml-0.5 min-h-4 pl-6 font-medium leading-none tracking-tight', className)} {...props} />;
}

function AlertDescription({ className, ...props }: React.ComponentProps<typeof Text> & React.RefAttributes<Text>) {
  const textClass = React.useContext(TextClassContext);
  return (
    <Text
      className={cn(
        'text-muted-foreground ml-0.5 pb-1.5 pl-6 text-sm leading-relaxed',
        textClass?.includes('text-destructive') && 'text-destructive/90',
        className
      )}
      {...props}
    />
  );
}

export { Alert, AlertDescription, AlertTitle };
`,

  Avatar: `import { cn } from '@/lib/utils';
import * as AvatarPrimitive from '@rn-primitives/avatar';

function Avatar({
  className,
  ...props
}: AvatarPrimitive.RootProps & React.RefAttributes<AvatarPrimitive.RootRef>) {
  return (
    <AvatarPrimitive.Root
      className={cn('relative flex size-8 shrink-0 overflow-hidden rounded-full', className)}
      {...props}
    />
  );
}

function AvatarImage({
  className,
  ...props
}: AvatarPrimitive.ImageProps & React.RefAttributes<AvatarPrimitive.ImageRef>) {
  return <AvatarPrimitive.Image className={cn('aspect-square size-full', className)} {...props} />;
}

function AvatarFallback({
  className,
  ...props
}: AvatarPrimitive.FallbackProps & React.RefAttributes<AvatarPrimitive.FallbackRef>) {
  return (
    <AvatarPrimitive.Fallback
      className={cn(
        'bg-muted flex size-full flex-row items-center justify-center rounded-full',
        className
      )}
      {...props}
    />
  );
}

export { Avatar, AvatarFallback, AvatarImage };
`,

  Badge: `import { TextClassContext } from '@/components/ui/text';
import { cn } from '@/lib/utils';
import * as Slot from '@rn-primitives/slot';
import { cva, type VariantProps } from 'class-variance-authority';
import { Platform, View, ViewProps } from 'react-native';

const badgeVariants = cva(
  cn(
    'border-border group shrink-0 flex-row items-center justify-center gap-1 overflow-hidden rounded-md border px-2 py-0.5',
    Platform.select({
      web: 'focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive w-fit whitespace-nowrap transition-[color,box-shadow] focus-visible:ring-[3px] [&>svg]:pointer-events-none [&>svg]:size-3',
    })
  ),
  {
    variants: {
      variant: {
        default: cn(
          'bg-primary border-transparent',
          Platform.select({ web: '[a&]:hover:bg-primary/90' })
        ),
        secondary: cn(
          'bg-secondary border-transparent',
          Platform.select({ web: '[a&]:hover:bg-secondary/90' })
        ),
        destructive: cn(
          'bg-destructive border-transparent',
          Platform.select({ web: '[a&]:hover:bg-destructive/90' })
        ),
        outline: Platform.select({ web: '[a&]:hover:bg-accent [a&]:hover:text-accent-foreground' }),
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  }
);

const badgeTextVariants = cva('text-xs font-medium', {
  variants: {
    variant: {
      default: 'text-primary-foreground',
      secondary: 'text-secondary-foreground',
      destructive: 'text-white',
      outline: 'text-foreground',
    },
  },
  defaultVariants: {
    variant: 'default',
  },
});

type BadgeProps = ViewProps &
  React.RefAttributes<View> & {
    asChild?: boolean;
  } & VariantProps<typeof badgeVariants>;

function Badge({ className, variant, asChild, ...props }: BadgeProps) {
  const Component = asChild ? Slot.View : View;
  return (
    <TextClassContext.Provider value={badgeTextVariants({ variant })}>
      <Component className={cn(badgeVariants({ variant }), className)} {...props} />
    </TextClassContext.Provider>
  );
}

export { Badge, badgeTextVariants, badgeVariants };
export type { BadgeProps };
`,

  Banner: `import { ComponentPropsWithoutRef, ElementRef, forwardRef, ReactNode } from 'react';
import { View, Text, Pressable } from 'react-native';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';
import Svg, { Path, Defs, Pattern, Image, Use } from 'react-native-svg';

const bannerVariants = cva('flex flex-row items-center', {
  variants: {
    variant: {
      'standard-app': 'bg-muted p-4 gap-5 h-[88px] w-full max-w-[393px]',
      welcome: 'p-0 gap-4 h-[40px] w-[329px]'
    }
  },
  defaultVariants: {
    variant: 'standard-app'
  }
});

const bannerTextVariants = cva('whitespace-nowrap', {
  variants: {
    variant: {
      'standard-app': 'text-foreground text-[12px] leading-[14px]',
      welcome: 'text-foreground text-[22px] leading-[28px] font-bold w-[273px]'
    }
  },
  defaultVariants: {
    variant: 'standard-app'
  }
});

type BannerProps = ComponentPropsWithoutRef<typeof View> &
  VariantProps<typeof bannerVariants> & {
    className?: string;
    title?: string;
    link?: string;
    trailingIcon?: ReactNode;
  };

const FlagIcon = ({ size = 31 }) => (
  <View style={{ width: size, height: (size * 22) / 31 }}>
    <Svg width={size} height={(size * 22) / 31} viewBox='0 0 31 22' fill='none'>
      <Path d='M0 0.69342V21.4307H30.1634V0.69342H0Z' fill='url(#pattern0)' />
      <Defs>
        <Pattern id='pattern0' patternContentUnits='objectBoundingBox' width={1} height={1}>
          <Use href='#image0' transform='scale(0.0625 0.0909091)' />
        </Pattern>
        <Image
          id='image0'
          width={16}
          height={11}
          href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAMAAABBPP0LAAAAG1BMVEUdM7EeNLIeM7HgQCDaPh/bPh/bPx/////bPyBEby41AAAAUElEQVQI123MNw4CABDEwD3jC/9/MQ1BQrgeOSkIqYe2o2FZtthXgQLgbHVMZdlsfUQFQnHtjP1+8BUhBDKOqtmfot6ojqPzR7TjdU+f6vkED+IDPhTBcMAAAAAASUVORK5CYII='
        />
      </Defs>
    </Svg>
  </View>
);

const Banner = forwardRef<ElementRef<typeof View>, BannerProps>(({ className, variant, title, link, trailingIcon, ...props }, ref) => {
  const isStandardApp = variant === 'standard-app';

  return (
    <View ref={ref} testID='banner' accessibilityRole='header' className={cn(bannerVariants({ variant, className }))} {...props}>
      {isStandardApp && (
        <>
          <FlagIcon />
          <View className='h-14 w-[1px] bg-border flex-shrink-0' />
        </>
      )}

      <View className={cn('flex flex-col', isStandardApp ? 'gap-3 flex-1' : 'gap-0')}>
        <Text className={bannerTextVariants({ variant })} numberOfLines={1}>
          {isStandardApp ? (
            <>
              <Text className='font-bold'>An official app</Text>
              <Text className='font-normal'> of the United States government</Text>
            </>
          ) : (
            title
          )}
        </Text>
        {isStandardApp && link && (
          <Pressable accessibilityRole='link' accessibilityLabel={link}>
            <Text className='text-primary text-[12px] leading-[14px] font-semibold underline whitespace-nowrap' numberOfLines={1}>
              {link}
            </Text>
          </Pressable>
        )}
      </View>

      {trailingIcon && (
        <View className='flex flex-row justify-center items-center w-[40px] h-[40px] p-2'>
          <View className='w-6 h-6'>{trailingIcon}</View>
        </View>
      )}
    </View>
  );
});

Banner.displayName = 'Banner';

export { Banner, type BannerProps };
`,

  Biometricsignin: `import { ComponentPropsWithoutRef, ElementRef, forwardRef } from 'react';
import { View, Text, Pressable } from 'react-native';
import * as CheckboxPrimitive from '@rn-primitives/checkbox';
import { cn } from '@/lib/utils';
import { Icon } from '@/components/ui/icon';
import { Check, ScanFace, Fingerprint } from 'lucide-react-native';
import { cssInterop } from 'nativewind';

cssInterop(CheckboxPrimitive.Root, { className: 'style' });
interface BiometricSignInProps extends ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root> {
  biometricType?: 'faceId' | 'touchId' | 'biometric';
  className?: string;
}

const BiometricSignIn = forwardRef<ElementRef<typeof CheckboxPrimitive.Root>, BiometricSignInProps>(
  ({ biometricType = 'faceId', className, disabled, checked, onCheckedChange, ...props }, ref) => {
    const handlePress = () => {
      if (!disabled && onCheckedChange) {
        onCheckedChange(!checked);
      }
    };

    const getBiometricText = () => {
      switch (biometricType) {
        case 'faceId':
          return 'Face ID';
        case 'touchId':
          return 'Touch ID';
        case 'biometric':
          return 'Biometric';
        default:
          return 'Face ID';
      }
    };

    const getBiometricIcon = () => {
      switch (biometricType) {
        case 'faceId':
          return <Icon as={ScanFace} size={20} className='text-foreground' />;
        case 'touchId':
          return <Icon as={Fingerprint} size={20} className='text-foreground' />;
        case 'biometric':
          return <Icon as={Fingerprint} size={20} className='text-foreground' />;
        default:
          return <Icon as={ScanFace} size={20} className='text-foreground' />;
      }
    };

    return (
      <Pressable onPress={handlePress} testID='biometric-pressable'>
        <View className={cn('flex-row items-center px-[15px] py-3 gap-3 w-[318.88px] h-[50px]', 'border border-base-ink rounded', className)}>
          <View className='flex-row items-center gap-2 flex-1'>
            <CheckboxPrimitive.Root
              ref={ref}
              testID='biometric-checkbox'
              accessibilityRole='checkbox'
              accessibilityState={{ checked, disabled }}
              disabled={disabled}
              checked={checked}
              onCheckedChange={onCheckedChange}
              {...props}
              className={cn(
                'w-6 h-6 border-2 rounded items-center justify-center flex-shrink-0',
                checked
                  ? disabled
                    ? 'bg-disabled border-disabled' // disabled state
                    : 'bg-primary border-primary' // checked state
                  : 'bg-transparent border-base-ink' // unchecked state
              )}
            >
              <CheckboxPrimitive.Indicator>
                <Icon as={Check} size={14} className='text-white' />
              </CheckboxPrimitive.Indicator>
            </CheckboxPrimitive.Root>

            <Text className='flex-1 text-base leading-5 text-base-ink'>Enable {getBiometricText()} for sign in</Text>
          </View>

          {getBiometricIcon()}
        </View>
      </Pressable>
    );
  }
);

BiometricSignIn.displayName = 'BiometricSignIn';

export { BiometricSignIn };
`,

  Button: `import { TextClassContext } from '@/components/ui/text';
import { cn } from '@/lib/utils';
import { cva, type VariantProps } from 'class-variance-authority';
import { Platform, Pressable } from 'react-native';

const buttonVariants = cva(
  cn(
    'group shrink-0 flex-row items-center justify-center gap-2 rounded-md shadow-none',
    Platform.select({
      web: "focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive whitespace-nowrap outline-none transition-all focus-visible:ring-[3px] disabled:pointer-events-none [&_svg:not([class*='size-'])]:size-4 [&_svg]:pointer-events-none [&_svg]:shrink-0"
    })
  ),
  {
    variants: {
      variant: {
        default: cn('bg-primary active:bg-primary/90 shadow-sm shadow-black/5', Platform.select({ web: 'hover:bg-primary/90' })),
        destructive: cn(
          'bg-destructive active:bg-destructive/90 dark:bg-destructive/60 shadow-sm shadow-black/5',
          Platform.select({
            web: 'hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40'
          })
        ),
        outline: cn(
          'border-border bg-background active:bg-accent dark:bg-input/30 dark:border-input dark:active:bg-input/50 border shadow-sm shadow-black/5',
          Platform.select({
            web: 'hover:bg-accent dark:hover:bg-input/50'
          })
        ),
        secondary: cn('bg-secondary active:bg-secondary/80 shadow-sm shadow-black/5', Platform.select({ web: 'hover:bg-secondary/80' })),
        ghost: cn('active:bg-accent dark:active:bg-accent/50', Platform.select({ web: 'hover:bg-accent dark:hover:bg-accent/50' })),
        link: ''
      },
      size: {
        default: cn('h-10 px-4 py-2 sm:h-9', Platform.select({ web: 'has-[>svg]:px-3' })),
        sm: cn('h-9 gap-1.5 rounded-md px-3 sm:h-8', Platform.select({ web: 'has-[>svg]:px-2.5' })),
        lg: cn('h-11 rounded-md px-6 sm:h-10', Platform.select({ web: 'has-[>svg]:px-4' })),
        icon: 'h-10 w-10 sm:h-9 sm:w-9'
      }
    },
    defaultVariants: {
      variant: 'default',
      size: 'default'
    }
  }
);

const buttonTextVariants = cva(cn('text-foreground text-sm font-medium', Platform.select({ web: 'pointer-events-none transition-colors' })), {
  variants: {
    variant: {
      default: 'text-primary-foreground',
      destructive: 'text-white',
      outline: cn('group-active:text-accent-foreground', Platform.select({ web: 'group-hover:text-accent-foreground' })),
      secondary: 'text-secondary-foreground',
      ghost: 'group-active:text-accent-foreground',
      link: cn('text-primary group-active:underline', Platform.select({ web: 'underline-offset-4 hover:underline group-hover:underline' }))
    },
    size: {
      default: '',
      sm: '',
      lg: '',
      icon: ''
    }
  },
  defaultVariants: {
    variant: 'default',
    size: 'default'
  }
});

type ButtonProps = React.ComponentProps<typeof Pressable> & React.RefAttributes<typeof Pressable> & VariantProps<typeof buttonVariants>;

function Button({ className, variant, size, ...props }: ButtonProps) {
  return (
    <TextClassContext.Provider value={buttonTextVariants({ variant, size })}>
      <Pressable className={cn(props.disabled && 'opacity-50', buttonVariants({ variant, size }), className)} role='button' {...props} />
    </TextClassContext.Provider>
  );
}

export { Button, buttonTextVariants, buttonVariants };
export type { ButtonProps };
`,

  Buttongroup: `import { View } from 'react-native';
import { cn } from '@/lib/utils';
import { ComponentPropsWithoutRef, forwardRef } from 'react';

interface ButtonGroupProps extends ComponentPropsWithoutRef<typeof View> {
  orientation?: 'horizontal' | 'vertical';
  gap?: number;
  className?: string;
}

const ButtonGroup = forwardRef<View, ButtonGroupProps>(({ className, orientation = 'vertical', gap = 8, style, ...props }, ref) => {
  return (
    <View
      ref={ref}
      className={cn('flex', orientation === 'vertical' ? 'flex-col' : 'flex-row', className)}
      style={[
        {
          gap,
          flexDirection: orientation === 'vertical' ? 'column' : 'row'
        },
        style
      ]}
      {...props}
    />
  );
});

ButtonGroup.displayName = 'ButtonGroup';

export { ButtonGroup };
`,

  Card: `import { Text, TextClassContext } from '@/components/ui/text';
import { cn } from '@/lib/utils';
import { View, type ViewProps } from 'react-native';

function Card({ className, ...props }: ViewProps & React.RefAttributes<View>) {
  return (
    <TextClassContext.Provider value="text-card-foreground">
      <View
        className={cn(
          'bg-card border-border flex flex-col gap-6 rounded-xl border py-6 shadow-sm shadow-black/5',
          className
        )}
        {...props}
      />
    </TextClassContext.Provider>
  );
}

function CardHeader({ className, ...props }: ViewProps & React.RefAttributes<View>) {
  return <View className={cn('flex flex-col gap-1.5 px-6', className)} {...props} />;
}

function CardTitle({
  className,
  ...props
}: React.ComponentProps<typeof Text> & React.RefAttributes<Text>) {
  return (
    <Text
      role="heading"
      aria-level={3}
      className={cn('font-semibold leading-none', className)}
      {...props}
    />
  );
}

function CardDescription({
  className,
  ...props
}: React.ComponentProps<typeof Text> & React.RefAttributes<Text>) {
  return <Text className={cn('text-muted-foreground text-sm', className)} {...props} />;
}

function CardContent({ className, ...props }: ViewProps & React.RefAttributes<View>) {
  return <View className={cn('px-6', className)} {...props} />;
}

function CardFooter({ className, ...props }: ViewProps & React.RefAttributes<View>) {
  return <View className={cn('flex flex-row items-center px-6', className)} {...props} />;
}

export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle };
`,

  Checkbox: `import { Icon } from '@/components/ui/icon';
import { cn } from '@/lib/utils';
import * as CheckboxPrimitive from '@rn-primitives/checkbox';
import { Check } from 'lucide-react-native';
import { Platform } from 'react-native';

const DEFAULT_HIT_SLOP = 24;

function Checkbox({
  className,
  checkedClassName,
  indicatorClassName,
  iconClassName,
  ...props
}: CheckboxPrimitive.RootProps &
  React.RefAttributes<CheckboxPrimitive.RootRef> & {
    checkedClassName?: string;
    indicatorClassName?: string;
    iconClassName?: string;
  }) {
  return (
    <CheckboxPrimitive.Root
      className={cn(
        'border-input dark:bg-input/30 size-4 shrink-0 rounded-[4px] border shadow-sm shadow-black/5',
        Platform.select({
          web: 'focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive peer cursor-default outline-none transition-shadow focus-visible:ring-[3px] disabled:cursor-not-allowed',
          native: 'overflow-hidden',
        }),
        props.checked && cn('border-primary', checkedClassName),
        props.disabled && 'opacity-50',
        className
      )}
      hitSlop={DEFAULT_HIT_SLOP}
      {...props}>
      <CheckboxPrimitive.Indicator
        className={cn('bg-primary h-full w-full items-center justify-center', indicatorClassName)}>
        <Icon
          as={Check}
          size={12}
          strokeWidth={Platform.OS === 'web' ? 2.5 : 3.5}
          className={cn('text-primary-foreground', iconClassName)}
        />
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
  );
}

export { Checkbox };
`,

  Checkboxtile: `import { ComponentPropsWithoutRef, ElementRef, forwardRef } from 'react';
import { View, Text, Pressable } from 'react-native';
import * as CheckboxPrimitive from '@rn-primitives/checkbox';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';
import { Icon } from '@/components/ui/icon';
import { Check } from 'lucide-react-native';
import { cssInterop } from 'nativewind';

cssInterop(CheckboxPrimitive.Root, { className: 'style' });

const checkboxTileVariants = cva('flex flex-col w-[329px] rounded-[2px] border-2', {
  variants: {
    variant: {
      default: 'gap-2.5',
      withDescription: 'gap-1.5'
    },
    state: {
      checked: 'bg-primary-lighter border-primary-light',
      unchecked: 'bg-background border-disabled-lighter',
      disabled: 'bg-background border-disabled-light'
    }
  },
  defaultVariants: {
    variant: 'default',
    state: 'unchecked'
  }
});

interface CheckboxTileProps extends ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>, VariantProps<typeof checkboxTileVariants> {
  label: string;
  description?: string;
  className?: string;
}

const CheckboxTile = forwardRef<ElementRef<typeof CheckboxPrimitive.Root>, CheckboxTileProps>(
  ({ label, description, className, disabled, checked, onCheckedChange, ...props }, ref) => {
    const handlePress = () => {
      if (!disabled && onCheckedChange) {
        onCheckedChange(!checked);
      }
    };

    const state = disabled ? 'disabled' : checked ? 'checked' : 'unchecked';
    const variant = description ? 'withDescription' : 'default';

    return (
      <Pressable onPress={handlePress} disabled={disabled}>
        <View className={cn(checkboxTileVariants({ variant, state }), 'p-[13px_16px_13px_9px]', className)}>
          <View className='flex flex-row gap-2'>
            <View className='w-5'>
              <CheckboxPrimitive.Root
                ref={ref}
                disabled={disabled}
                checked={checked}
                onCheckedChange={onCheckedChange}
                {...props}
                className={cn(
                  'w-5 h-5 border-2 rounded items-center justify-center flex-shrink-0',
                  checked ? (disabled ? 'bg-disabled border-disabled' : 'bg-primary border-primary') : 'bg-transparent border-base-ink'
                )}
              >
                <CheckboxPrimitive.Indicator>
                  <Icon as={Check} size={14} className='text-white' />
                </CheckboxPrimitive.Indicator>
              </CheckboxPrimitive.Root>
            </View>

            <View className='flex-1 flex-col gap-1.5'>
              <Text className={cn('text-base leading-5', disabled ? 'text-disabled' : 'text-base-ink')}>{label}</Text>

              {description && <Text className={cn('text-base leading-5', disabled ? 'text-disabled' : 'text-base-ink')}>{description}</Text>}
            </View>
          </View>
        </View>
      </Pressable>
    );
  }
);

CheckboxTile.displayName = 'CheckboxTile';

export { CheckboxTile, type CheckboxTileProps };
`,

  Collapsible: `import * as CollapsiblePrimitive from '@rn-primitives/collapsible';

const Collapsible = CollapsiblePrimitive.Root;

const CollapsibleTrigger = CollapsiblePrimitive.Trigger;

const CollapsibleContent = CollapsiblePrimitive.Content;

export { Collapsible, CollapsibleTrigger, CollapsibleContent };`,

  Dialog: `import { Icon } from '@/components/ui/icon';
import { cn } from '@/lib/utils';
import * as DialogPrimitive from '@rn-primitives/dialog';
import { X } from 'lucide-react-native';
import * as React from 'react';
import { Platform, Text, View, type ViewProps } from 'react-native';
import { FadeIn, FadeOut } from 'react-native-reanimated';
import Animated from 'react-native-reanimated';

const Dialog = DialogPrimitive.Root;

const DialogTrigger = DialogPrimitive.Trigger;

const DialogPortal = DialogPrimitive.Portal;

const DialogClose = DialogPrimitive.Close;

const AnimatedPressable = Animated.createAnimatedComponent(View);

function DialogOverlay({
  className,
  children,
  ...props
}: Omit<DialogPrimitive.OverlayProps, 'asChild'> &
  React.RefAttributes<DialogPrimitive.OverlayRef> & {
    children?: React.ReactNode;
  }) {
  return (
    <DialogPrimitive.Overlay
      className={cn(
        'absolute bottom-0 left-0 right-0 top-0 z-50 flex items-center justify-center bg-black/50 p-2',
        Platform.select({
          web: 'animate-in fade-in-0 fixed cursor-default [&>*]:cursor-auto',
        }),
        className
      )}
      {...props}
      asChild={Platform.OS !== 'web'}>
      <AnimatedPressable entering={FadeIn.duration(200)} exiting={FadeOut.duration(150)}>
        <AnimatedPressable entering={FadeIn.delay(50)} exiting={FadeOut.duration(150)}>
          <>{children}</>
        </AnimatedPressable>
      </AnimatedPressable>
    </DialogPrimitive.Overlay>
  );
}

function DialogContent({
  className,
  portalHost,
  children,
  ...props
}: DialogPrimitive.ContentProps &
  React.RefAttributes<DialogPrimitive.ContentRef> & {
    portalHost?: string;
  }) {
  return (
    <DialogPortal hostName={portalHost}>
      <DialogOverlay>
        <DialogPrimitive.Content
          className={cn(
            'bg-background border-border z-50 mx-auto flex w-full max-w-[calc(100%-2rem)] flex-col gap-4 rounded-lg border p-6 shadow-lg shadow-black/5 sm:max-w-lg',
            Platform.select({
              web: 'animate-in fade-in-0 zoom-in-95 duration-200',
            }),
            className
          )}
          {...props}>
          <>{children}</>
          <DialogPrimitive.Close
            className={cn(
              'absolute right-4 top-4 rounded opacity-70 active:opacity-100',
              Platform.select({
                web: 'ring-offset-background focus:ring-ring data-[state=open]:bg-accent transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-offset-2',
              })
            )}
            hitSlop={12}>
            <Icon
              as={X}
              className={cn('text-accent-foreground web:pointer-events-none size-4 shrink-0')}
            />
            <Text className="sr-only">Close</Text>
          </DialogPrimitive.Close>
        </DialogPrimitive.Content>
      </DialogOverlay>
    </DialogPortal>
  );
}

function DialogHeader({ className, ...props }: ViewProps) {
  return (
    <View className={cn('flex flex-col gap-2 text-center sm:text-left', className)} {...props} />
  );
}

function DialogFooter({ className, ...props }: ViewProps) {
  return (
    <View
      className={cn('flex flex-col-reverse gap-2 sm:flex-row sm:justify-end', className)}
      {...props}
    />
  );
}

function DialogTitle({
  className,
  ...props
}: DialogPrimitive.TitleProps & React.RefAttributes<DialogPrimitive.TitleRef>) {
  return (
    <DialogPrimitive.Title
      className={cn('text-foreground text-lg font-semibold leading-none', className)}
      {...props}
    />
  );
}

function DialogDescription({
  className,
  ...props
}: DialogPrimitive.DescriptionProps & React.RefAttributes<DialogPrimitive.DescriptionRef>) {
  return (
    <DialogPrimitive.Description
      className={cn('text-muted-foreground text-sm', className)}
      {...props}
    />
  );
}

export {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
};
`,

  Icon: `import { cn } from '@/lib/utils';
import type { LucideIcon, LucideProps } from 'lucide-react-native';
import { cssInterop } from 'nativewind';

type IconProps = LucideProps & {
  as: LucideIcon;
};

function IconImpl({ as: IconComponent, ...props }: IconProps) {
  return <IconComponent {...props} />;
}

cssInterop(IconImpl, {
  className: {
    target: 'style',
    nativeStyleToProp: {
      height: 'size',
      width: 'size'
    }
  }
});

/**
 * A wrapper component for Lucide icons with Nativewind \`className\` support via \`cssInterop\`.
 *
 * This component allows you to render any Lucide icon while applying utility classes
 * using \`nativewind\`. It avoids the need to wrap or configure each icon individually.
 *
 * @component
 * @example
 * \`\`\`tsx
 * import { ArrowRight } from 'lucide-react-native';
 * import { Icon } from '@/components/ui/icon';
 *
 * <Icon as={ArrowRight} className="text-red-500" size={16} />
 * \`\`\`
 *
 * @param {LucideIcon} as - The Lucide icon component to render.
 * @param {string} className - Utility classes to style the icon using Nativewind.
 * @param {number} size - Icon size (defaults to 14).
 * @param {...LucideProps} ...props - Additional Lucide icon props passed to the "as" icon.
 */
function Icon({ as: IconComponent, className, size = 14, ...props }: IconProps) {
  return <IconImpl as={IconComponent} className={cn('text-foreground', className)} size={size} {...props} />;
}

export { Icon };
export type { IconProps };
`,

  Link: `import { ComponentPropsWithoutRef, forwardRef, useState } from 'react';
import { Text, Pressable, View, Platform } from 'react-native';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';
import { Icon } from '@/components/ui/icon';
import { ExternalLink } from 'lucide-react-native';

const linkVariants = cva(cn('text-base leading-[162%] underline', Platform.select({ web: 'cursor-pointer' })), {
  variants: {
    variant: {
      default: 'text-primary',
      visited: 'text-secondary',
      'dark-background': 'text-primary'
    },
    external: {
      true: 'flex-row items-center gap-0.5',
      false: ''
    },
    focus: {
      true: cn('outline-none rounded', Platform.select({ web: 'ring-4 ring-ring' })),
      false: ''
    }
  },
  defaultVariants: {
    variant: 'default',
    external: false,
    focus: false
  }
});

interface LinkProps extends ComponentPropsWithoutRef<typeof Pressable>, VariantProps<typeof linkVariants> {
  href: string;
  label: string;
  className?: string;
  visited?: boolean;
  variant?: 'default' | 'visited' | 'dark-background';
  external?: boolean;
  focus?: boolean;
}

const Link = forwardRef<View, LinkProps>(({ href, label, className, external, visited, focus, ...props }, ref) => {
  const [isPressed, setIsPressed] = useState(false);
  const variant = visited ? 'visited' : props.variant;

  return (
    <Pressable
      ref={ref}
      onPressIn={() => setIsPressed(true)}
      onPressOut={() => setIsPressed(false)}
      className={cn(linkVariants({ variant, external, focus }), className)}
      accessibilityRole='link'
      {...props}
    >
      {({ pressed }) => (
        <View className={cn(linkVariants({ variant, external, focus: pressed || isPressed || focus }))}>
          <Text className={linkVariants({ variant, external, focus: pressed || isPressed || focus })}>{label}</Text>
          {external && (
            <Icon
              as={ExternalLink}
              size={14}
              className={cn(visited ? 'text-secondary' : 'text-primary')}
            />
          )}
        </View>
      )}
    </Pressable>
  );
});

Link.displayName = 'Link';

export { Link };
`,

  Pagination: `import { ComponentPropsWithoutRef, forwardRef } from 'react';
import { View, Text, Pressable } from 'react-native';
import { cn } from '@/lib/utils';
import { Icon } from '@/components/ui/icon';
import { ChevronLeft, ChevronRight } from 'lucide-react-native';

interface PaginationProps extends ComponentPropsWithoutRef<typeof View> {
  currentPage: number;
  totalPages: number;
  totalItems: number;
  onPageChange: (page: number) => void;
  className?: string;
}

const PaginationButton = forwardRef<View, ComponentPropsWithoutRef<typeof Pressable> & { active?: boolean }>(
  ({ children, active, disabled, className, ...props }, ref) => {
    return (
      <Pressable
        ref={ref}
        className={cn(
          'w-[50px] h-[50px] rounded justify-center items-center',
          active ? 'bg-primary' : disabled ? 'bg-muted' : 'bg-primary',
          className
        )}
        disabled={disabled}
        accessible={true}
        {...props}
      >
        {children}
      </Pressable>
    );
  }
);

const Pagination = ({ currentPage, totalPages, totalItems, onPageChange, className }: PaginationProps) => {
  const handlePrevious = () => {
    if (currentPage > 1) {
      onPageChange(currentPage - 1);
    }
  };

  const handleNext = () => {
    if (currentPage < totalPages) {
      onPageChange(currentPage + 1);
    }
  };

  return (
    <View className={cn('flex-row items-center p-8 gap-3 bg-accent w-[393px]', className)}>
      <PaginationButton
        onPress={handlePrevious}
        disabled={currentPage === 1}
        className={currentPage === 1 ? 'bg-muted' : 'bg-primary'}
        accessibilityLabel='Previous page'
        accessibilityRole='button'
        accessibilityState={{ disabled: currentPage === 1 }}
        testID='previous-button'
      >
        <Icon as={ChevronLeft} size={24} className='text-primary-foreground' />
      </PaginationButton>

      <Text className='flex-1 text-center text-[20px] leading-[30px] text-foreground'>
        {currentPage} to {totalPages} of {totalItems}
      </Text>

      <PaginationButton
        onPress={handleNext}
        disabled={currentPage === totalPages}
        className={currentPage === totalPages ? 'bg-muted' : 'bg-primary'}
        accessibilityLabel='Next page'
        accessibilityRole='button'
        accessibilityState={{ disabled: currentPage === totalPages }}
        testID='next-button'
      >
        <Icon as={ChevronRight} size={24} className='text-primary-foreground' />
      </PaginationButton>
    </View>
  );
};

PaginationButton.displayName = 'PaginationButton';
Pagination.displayName = 'Pagination';

export { Pagination };
`,

  Progress: `import { cn } from '@/lib/utils';
import * as ProgressPrimitive from '@rn-primitives/progress';
import { Platform, View } from 'react-native';
import Animated, {
  Extrapolation,
  interpolate,
  useAnimatedStyle,
  useDerivedValue,
  withSpring,
} from 'react-native-reanimated';

function Progress({
  className,
  value,
  indicatorClassName,
  ...props
}: ProgressPrimitive.RootProps &
  React.RefAttributes<ProgressPrimitive.RootRef> & {
    indicatorClassName?: string;
  }) {
  return (
    <ProgressPrimitive.Root
      className={cn('bg-primary/20 relative h-2 w-full overflow-hidden rounded-full', className)}
      {...props}>
      <Indicator value={value} className={indicatorClassName} />
    </ProgressPrimitive.Root>
  );
}

export { Progress };

const Indicator = Platform.select({
  web: WebIndicator,
  native: NativeIndicator,
  default: NullIndicator,
});

type IndicatorProps = {
  value: number | undefined | null;
  className?: string;
};

function WebIndicator({ value, className }: IndicatorProps) {
  if (Platform.OS !== 'web') {
    return null;
  }

  return (
    <View
      className={cn('bg-primary h-full w-full flex-1 transition-all', className)}
      style={{ transform: \`translateX(-\${100 - (value ?? 0)}%)\` }}>
      <ProgressPrimitive.Indicator className={cn('h-full w-full', className)} />
    </View>
  );
}

function NativeIndicator({ value, className }: IndicatorProps) {
  const progress = useDerivedValue(() => value ?? 0);

  const indicator = useAnimatedStyle(() => {
    return {
      width: withSpring(
        \`\${interpolate(progress.value, [0, 100], [1, 100], Extrapolation.CLAMP)}%\`,
        { overshootClamping: true }
      ),
    };
  }, [value]);

  if (Platform.OS === 'web') {
    return null;
  }

  return (
    <ProgressPrimitive.Indicator asChild>
      <Animated.View style={indicator} className={cn('bg-foreground h-full', className)} />
    </ProgressPrimitive.Indicator>
  );
}

function NullIndicator(_props: IndicatorProps) {
  return null;
}
`,

  Radiobutton: `import { ComponentPropsWithoutRef, ElementRef, forwardRef, useContext, createContext } from 'react';
import { View, Text, Pressable, GestureResponderEvent, Platform } from 'react-native';
import * as RadioGroupPrimitive from '@rn-primitives/radio-group';
import { cn } from '@/lib/utils';
import { cssInterop } from 'nativewind';

cssInterop(RadioGroupPrimitive.Root, { className: 'style' });
cssInterop(RadioGroupPrimitive.Item, { className: 'style' });
cssInterop(RadioGroupPrimitive.Indicator, { className: 'style' });

const RadioContext = createContext<{ value?: string }>({});
interface RadioButtonProps extends ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Item> {
  label: string;
  className?: string;
}

const RadioGroup = forwardRef<ElementRef<typeof RadioGroupPrimitive.Root>, ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Root>>(
  ({ ...props }, ref) => {
    return (
      <RadioContext.Provider value={{ value: props.value }}>
        <RadioGroupPrimitive.Root ref={ref} {...props}>
          <View className='flex flex-col gap-3'>{props.children}</View>
        </RadioGroupPrimitive.Root>
      </RadioContext.Provider>
    );
  }
);

const RadioButton = forwardRef<ElementRef<typeof RadioGroupPrimitive.Item>, RadioButtonProps>(({ label, className, ...props }, ref) => {
  const labelId = \`\${props.value}-label\`;
  const { value } = useContext(RadioContext);
  const isSelected = value === props.value;

  const handlePress = (event: GestureResponderEvent) => {
    if (!props.disabled && props.onPress) {
      props.onPress(event);
    }
  };

  return (
    <Pressable
      accessibilityRole='radio'
      accessibilityState={{ checked: isSelected, disabled: props.disabled || false }}
      onPress={handlePress}
      className='flex flex-row items-center gap-2 min-h-[44px] w-[329px] px-4'
    >
      <RadioGroupPrimitive.Item
        ref={ref}
        aria-labelledby={labelId}
        testID={\`radio-\${props.value}\`}
        className={cn(
          Platform.OS === 'web' ? 'w-5 h-5' : 'min-w-[20px] min-h-[20px] w-5 h-5',
          'rounded-full border-2 flex items-center justify-center bg-background',
          props.disabled ? 'border-muted-foreground' : isSelected ? 'border-primary' : 'border-foreground'
        )}
        {...props}
      >
        <RadioGroupPrimitive.Indicator forceMount className={Platform.OS === 'web' ? 'flex items-center justify-center' : 'w-full h-full flex items-center justify-center'}>
          <View className={cn('h-[10px] w-[10px] rounded-full', isSelected ? (props.disabled ? 'bg-muted-foreground' : 'bg-primary') : 'bg-transparent')} />
        </RadioGroupPrimitive.Indicator>
      </RadioGroupPrimitive.Item>

      <Text nativeID={labelId} className={cn('flex-1 text-base leading-5', props.disabled ? 'text-muted-foreground' : 'text-foreground')}>
        {label}
      </Text>
    </Pressable>
  );
});

RadioButton.displayName = 'RadioButton';
RadioGroup.displayName = 'RadioGroup';

export { RadioGroup, RadioButton };
`,

  Radiotile: `import { ComponentPropsWithoutRef, ElementRef, forwardRef, useContext, createContext } from 'react';
import { View, Text, Pressable, GestureResponderEvent } from 'react-native';
import * as RadioGroupPrimitive from '@rn-primitives/radio-group';
import { cn } from '@/lib/utils';
import { cva, type VariantProps } from 'class-variance-authority';
import { cssInterop } from 'nativewind';

cssInterop(RadioGroupPrimitive.Root, { className: 'style' });
cssInterop(RadioGroupPrimitive.Item, { className: 'style' });
cssInterop(RadioGroupPrimitive.Indicator, { className: 'style' });

const RadioContext = createContext<{ value?: string; onValueChange?: (value: string) => void }>({});

const radioTileVariants = cva('flex flex-col w-[329px] rounded-[2px] border-2', {
  variants: {
    variant: {
      default: '',
      withDescription: 'gap-2'
    },
    state: {
      checked: 'bg-primary-lighter border-primary',
      unchecked: 'bg-background border-disabled-lighter',
      disabled: 'bg-background border-muted'
    }
  },
  defaultVariants: {
    variant: 'default',
    state: 'unchecked'
  }
});

const radioItemVariants = cva('aspect-square h-5 w-5 rounded-full border-2 bg-background', {
  variants: {
    state: {
      checked: 'border-primary',
      unchecked: 'border-foreground',
      disabled: 'border-disabled'
    }
  },
  defaultVariants: {
    state: 'unchecked'
  }
});

const radioIndicatorVariants = cva('h-[10px] w-[10px] rounded-full', {
  variants: {
    state: {
      checked: 'bg-primary',
      disabled: 'bg-disabled'
    }
  },
  defaultVariants: {
    state: 'checked'
  }
});

interface RadioTileProps extends ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Item>, VariantProps<typeof radioTileVariants> {
  label: string;
  description?: string;
  className?: string;
  variant?: 'default' | 'withDescription';
}

const RadioTileGroup = forwardRef<ElementRef<typeof RadioGroupPrimitive.Root>, ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Root>>(
  ({ ...props }, ref) => {
    return (
      <RadioContext.Provider value={{ value: props.value, onValueChange: props.onValueChange }}>
        <RadioGroupPrimitive.Root ref={ref} {...props}>
          <View className='flex flex-col gap-3'>{props.children}</View>
        </RadioGroupPrimitive.Root>
      </RadioContext.Provider>
    );
  }
);

const RadioTile = forwardRef<ElementRef<typeof RadioGroupPrimitive.Item>, RadioTileProps>(
  ({ label, description, className, variant = description ? 'withDescription' : 'default', ...props }, ref) => {
    const labelId = \`\${props.value}-label\`;
    const descriptionId = \`\${props.value}-description\`;
    const { value, onValueChange } = useContext(RadioContext);
    const isSelected = value === props.value;

    const state = props.disabled ? 'disabled' : isSelected ? 'checked' : 'unchecked';

    const handlePress = (event: GestureResponderEvent) => {
      if (!props.disabled && onValueChange) {
        onValueChange(props.value);
      }
    };

    return (
      <Pressable onPress={handlePress} disabled={props.disabled}>
        <View className={cn(radioTileVariants({ variant, state }), 'p-[13px_16px_13px_9px]', className)}>
          <View className='flex flex-row items-center gap-2 min-h-[44px]'>
            <View className={cn(radioItemVariants({ state }), 'flex items-center justify-center')}>
              <RadioGroupPrimitive.Item
                ref={ref}
                aria-labelledby={labelId}
                aria-describedby={description ? descriptionId : undefined}
                className='w-full h-full items-center justify-center'
                {...props}
              >
                <RadioGroupPrimitive.Indicator className='items-center justify-center'>
                  <View className={cn(radioIndicatorVariants({ state: props.disabled ? 'disabled' : 'checked' }))} />
                </RadioGroupPrimitive.Indicator>
              </RadioGroupPrimitive.Item>
            </View>
            <Text nativeID={labelId} className={cn('flex-1 text-base leading-5', props.disabled ? 'text-disabled' : 'text-base-ink')}>
              {label}
            </Text>
          </View>
          {description && (
            <Text nativeID={descriptionId} className={cn('pl-7 text-[15px] leading-[19px]', props.disabled ? 'text-disabled' : 'text-base-ink')}>
              {description}
            </Text>
          )}
        </View>
      </Pressable>
    );
  }
);

RadioTileGroup.displayName = 'RadioTileGroup';
RadioTile.displayName = 'RadioTile';

export { RadioTile, RadioTileGroup };
export type { RadioTileProps };
`,

  Snackbar: `import { ComponentPropsWithoutRef, ElementRef, forwardRef } from 'react';
import { View, Text, Pressable } from 'react-native';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';
import { Icon } from '@/components/ui/icon';
import { Check, AlertCircle } from 'lucide-react-native';

const snackbarVariants = cva('flex w-[329px] bg-foreground rounded-[4px] p-3', {
  variants: {
    layout: {
      'one-line': 'flex-row items-center h-[48px] justify-between',
      'two-lines': 'min-h-[70px]'
    }
  },
  defaultVariants: {
    layout: 'one-line'
  }
});

type SnackbarProps = ComponentPropsWithoutRef<typeof View> &
  VariantProps<typeof snackbarVariants> & {
    className?: string;
    message: string;
    variant?: 'success' | 'error';
    onAction?: () => void;
    onDismiss?: () => void;
    actionLabel?: string;
  };

const Snackbar = forwardRef<ElementRef<typeof View>, SnackbarProps & { isVisible: boolean }>(
  ({ className, layout, message, variant = 'success', onAction, onDismiss, actionLabel = 'Action', isVisible }, ref) => {
    if (!isVisible) return null;

    const IconComponent = variant === 'success' ? Check : AlertCircle;

    if (layout === 'two-lines') {
      return (
        <View ref={ref} testID='snackbar-container' className={cn(snackbarVariants({ layout }), className)}>
          <View className='flex flex-row gap-2 mb-3'>
            <View className='flex items-center justify-center h-6'>
              <Icon as={IconComponent} size={24} className='bg-background text-foreground rounded-full' />
            </View>
            <Text className='text-background text-base leading-6 flex-1 flex-wrap'>{message}</Text>
          </View>

          <View className='flex flex-row justify-end items-center gap-6'>
            {onAction && (
              <Pressable onPress={onAction}>
                <Text className='text-background text-[15px] leading-[19px] font-bold'>{actionLabel}</Text>
              </Pressable>
            )}
            {onDismiss && (
              <Pressable onPress={onDismiss}>
                <Text className='text-background text-[15px] leading-[19px] font-bold'>Dismiss</Text>
              </Pressable>
            )}
          </View>
        </View>
      );
    }

    return (
      <View ref={ref} testID='snackbar-container' className={cn(snackbarVariants({ layout }), className)}>
        <View className='flex flex-row items-center gap-2 flex-shrink min-w-0 max-w-[171px]'>
          <View className='flex items-center justify-center h-6 flex-shrink-0'>
            <Icon as={IconComponent} size={24} className='bg-background text-foreground rounded-full' />
          </View>
          <Text numberOfLines={1} className='text-background text-base leading-6 flex-shrink'>
            {message}
          </Text>
        </View>

        <View className='flex flex-row items-center gap-6 flex-shrink-0'>
          {onAction && (
            <Pressable onPress={onAction}>
              <Text className='text-background text-[15px] leading-[19px] font-bold'>{actionLabel}</Text>
            </Pressable>
          )}
          {onDismiss && (
            <Pressable onPress={onDismiss}>
              <Text className='text-background text-[15px] leading-[19px] font-bold'>Dismiss</Text>
            </Pressable>
          )}
        </View>
      </View>
    );
  }
);

Snackbar.displayName = 'Snackbar';

export { Snackbar, type SnackbarProps };
`,

  Stepindicator: `import { ComponentPropsWithoutRef, forwardRef } from 'react';
import { View, Text } from 'react-native';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';

const stepIndicatorVariants = cva('flex flex-col items-center justify-center mx-auto', {
  variants: {
    size: {
      default: 'w-[329px] h-[68px]',
      small: 'w-[329px] h-[50px]'
    }
  },
  defaultVariants: {
    size: 'default'
  }
});

const segmentVariants = cva('flex flex-row items-center gap-1', {
  variants: {
    state: {
      default: 'bg-muted',
      active: 'bg-primary',
      complete: 'bg-secondary'
    },
    size: {
      default: 'h-12',
      small: 'h-8'
    }
  },
  defaultVariants: {
    state: 'default',
    size: 'default'
  }
});

interface StepIndicatorProps extends ComponentPropsWithoutRef<typeof View>, VariantProps<typeof stepIndicatorVariants> {
  steps: number;
  currentStep: number;
  title: string;
  labels?: string[];
}

const StepIndicator = forwardRef<View, StepIndicatorProps>(({ steps, currentStep, title, labels, size, className, ...props }, ref) => {
  return (
    <View ref={ref} className={cn(stepIndicatorVariants({ size }), className)} {...props}>
      {/* Segments container */}
      <View className='flex flex-row items-center justify-center gap-1 mb-4 w-full'>
        {Array.from({ length: steps }).map((_, index) => {
          const state = index < currentStep - 1 ? 'complete' : index === currentStep - 1 ? 'active' : 'default';

          return <View key={index} className={cn(segmentVariants({ state, size }), 'flex-1 h-3', index === steps - 1 && 'flex-none')} />;
        })}
      </View>

      {/* Heading */}
      <View className='flex flex-row items-center gap-2 w-full'>
        <View className={cn('rounded-full flex items-center justify-center', size === 'default' ? 'w-10 h-10' : 'w-6 h-6', 'bg-primary')}>
          <Text className='text-primary-foreground font-normal'>{currentStep}</Text>
        </View>
        <Text className='text-primary font-normal'>of {steps}</Text>
        <Text className='text-foreground font-bold text-[22px] leading-7'>{title}</Text>
      </View>
    </View>
  );
});

StepIndicator.displayName = 'StepIndicator';

export { StepIndicator };
`,

  Tag: `import { ComponentPropsWithoutRef, forwardRef } from 'react';
import { View, Text } from 'react-native';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';

const tagVariants = cva('flex flex-row justify-center items-center bg-foreground rounded-[2px]', {
  variants: {
    size: {
      default: 'px-2 py-0.5 h-[18px]',
      big: 'px-2 py-1 h-[24px]'
    }
  },
  defaultVariants: {
    size: 'default'
  }
});

const tagTextVariants = cva('text-background font-normal text-center', {
  variants: {
    size: {
      default: 'text-[14px] leading-[14px]',
      big: 'text-[16px] leading-[16px]'
    }
  },
  defaultVariants: {
    size: 'default'
  }
});

interface TagProps extends ComponentPropsWithoutRef<typeof View>, VariantProps<typeof tagVariants> {
  label: string;
  className?: string;
  size?: 'default' | 'big';
}

const Tag = forwardRef<View, TagProps>(({ label, size, className, ...props }, ref) => {
  return (
    <View ref={ref} style={{ minWidth: 43 }} className={cn(tagVariants({ size }), className)} {...props}>
      <Text className={tagTextVariants({ size })}>{label}</Text>
    </View>
  );
});

Tag.displayName = 'Tag';

export { Tag };
`,

  Text: `import { cn } from '@/lib/utils';
import * as Slot from '@rn-primitives/slot';
import { cva, type VariantProps } from 'class-variance-authority';
import * as React from 'react';
import { Platform, Text as RNText, type Role } from 'react-native';

const textVariants = cva(
  cn(
    'text-foreground text-base',
    Platform.select({
      web: 'select-text',
    })
  ),
  {
    variants: {
      variant: {
        default: '',
        h1: cn(
          'text-center text-4xl font-extrabold tracking-tight',
          Platform.select({ web: 'scroll-m-20 text-balance' })
        ),
        h2: cn(
          'border-border border-b pb-2 text-3xl font-semibold tracking-tight',
          Platform.select({ web: 'scroll-m-20 first:mt-0' })
        ),
        h3: cn('text-2xl font-semibold tracking-tight', Platform.select({ web: 'scroll-m-20' })),
        h4: cn('text-xl font-semibold tracking-tight', Platform.select({ web: 'scroll-m-20' })),
        p: 'mt-3 leading-7 sm:mt-6',
        blockquote: 'mt-4 border-l-2 pl-3 italic sm:mt-6 sm:pl-6',
        code: cn(
          'bg-muted relative rounded px-[0.3rem] py-[0.2rem] font-mono text-sm font-semibold'
        ),
        lead: 'text-muted-foreground text-xl',
        large: 'text-lg font-semibold',
        small: 'text-sm font-medium leading-none',
        muted: 'text-muted-foreground text-sm',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  }
);

type TextVariantProps = VariantProps<typeof textVariants>;

type TextVariant = NonNullable<TextVariantProps['variant']>;

const ROLE: Partial<Record<TextVariant, Role>> = {
  h1: 'heading',
  h2: 'heading',
  h3: 'heading',
  h4: 'heading',
  blockquote: Platform.select({ web: 'blockquote' as Role }),
  code: Platform.select({ web: 'code' as Role }),
};

const ARIA_LEVEL: Partial<Record<TextVariant, string>> = {
  h1: '1',
  h2: '2',
  h3: '3',
  h4: '4',
};

const TextClassContext = React.createContext<string | undefined>(undefined);

function Text({
  className,
  asChild = false,
  variant = 'default',
  ...props
}: React.ComponentProps<typeof RNText> &
  TextVariantProps &
  React.RefAttributes<RNText> & {
    asChild?: boolean;
  }) {
  const textClass = React.useContext(TextClassContext);
  const Component = asChild ? Slot.Text : RNText;
  return (
    <Component
      className={cn(textVariants({ variant }), textClass, className)}
      role={variant ? ROLE[variant] : undefined}
      aria-level={variant ? ARIA_LEVEL[variant] : undefined}
      {...props}
    />
  );
}

export { Text, TextClassContext, textVariants };
export type { TextVariantProps };
`,

  Textarea: `import { cn } from '@/lib/utils';
import { Platform, TextInput, type TextInputProps } from 'react-native';

function Textarea({
  className,
  multiline = true,
  numberOfLines = Platform.select({ web: 2, native: 8 }),
  placeholderClassName,
  ...props
}: TextInputProps & React.RefAttributes<TextInput>) {
  return (
    <TextInput
      className={cn(
        'text-foreground border-input dark:bg-input/30 flex min-h-16 w-full flex-row rounded-md border bg-transparent px-3 py-2 text-base shadow-sm shadow-black/5 md:text-sm',
        Platform.select({
          web: 'placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive field-sizing-content resize-y outline-none transition-[color,box-shadow] focus-visible:ring-[3px] disabled:cursor-not-allowed',
        }),
        props.editable === false && 'opacity-50',
        className
      )}
      placeholderClassName={cn('text-muted-foreground', placeholderClassName)}
      multiline={multiline}
      numberOfLines={numberOfLines}
      textAlignVertical="top"
      {...props}
    />
  );
}

export { Textarea };
`,

  Textinput: `import { cn } from '@/lib/utils';
import { Platform, TextInput as RNTextInput, type TextInputProps } from 'react-native';

function TextInput({
  className,
  ...props
}: TextInputProps & React.RefAttributes<RNTextInput>) {
  return (
    <RNTextInput
      className={cn(
        'dark:bg-input/30 border-input bg-background text-foreground flex h-10 w-full min-w-0 flex-row items-center rounded-md border px-3 py-1 text-base leading-5 shadow-sm shadow-black/5 sm:h-9',
        props.editable === false &&
          cn(
            'opacity-50',
            Platform.select({ web: 'disabled:pointer-events-none disabled:cursor-not-allowed' })
          ),
        Platform.select({
          web: cn(
            'placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground outline-none transition-[color,box-shadow] md:text-sm',
            'focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]',
            'aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive'
          ),
          native: 'placeholder:text-muted-foreground/50',
        }),
        className
      )}
      {...props}
    />
  );
}

export { TextInput };
`,

  Toggle: `import { Icon } from '@/components/ui/icon';
import { TextClassContext } from '@/components/ui/text';
import { cn } from '@/lib/utils';
import * as TogglePrimitive from '@rn-primitives/toggle';
import { cva, type VariantProps } from 'class-variance-authority';
import * as React from 'react';
import { Platform } from 'react-native';

const toggleVariants = cva(
  cn(
    'active:bg-muted group flex flex-row items-center justify-center gap-2 rounded-md',
    Platform.select({
      web: 'hover:bg-muted hover:text-muted-foreground focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive inline-flex cursor-default whitespace-nowrap outline-none transition-[color,box-shadow] focus-visible:ring-[3px] disabled:pointer-events-none [&_svg]:pointer-events-none',
    })
  ),
  {
    variants: {
      variant: {
        default: 'bg-transparent',
        outline: cn(
          'border-input active:bg-accent border bg-transparent shadow-sm shadow-black/5',
          Platform.select({
            web: 'hover:bg-accent hover:text-accent-foreground',
          })
        ),
      },
      size: {
        default: 'h-10 min-w-10 px-2.5 sm:h-9 sm:min-w-9 sm:px-2',
        sm: 'h-9 min-w-9 px-2 sm:h-8 sm:min-w-8 sm:px-1.5',
        lg: 'h-11 min-w-11 px-3 sm:h-10 sm:min-w-10 sm:px-2.5',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  }
);

function Toggle({
  className,
  variant,
  size,
  ...props
}: TogglePrimitive.RootProps &
  VariantProps<typeof toggleVariants> &
  React.RefAttributes<TogglePrimitive.RootRef>) {
  return (
    <TextClassContext.Provider
      value={cn(
        'text-sm text-foreground font-medium',
        props.pressed
          ? 'text-accent-foreground'
          : Platform.select({ web: 'group-hover:text-muted-foreground' }),
        className
      )}>
      <TogglePrimitive.Root
        className={cn(
          toggleVariants({ variant, size }),
          props.disabled && 'opacity-50',
          props.pressed && 'bg-accent',
          className
        )}
        {...props}
      />
    </TextClassContext.Provider>
  );
}

function ToggleIcon({ className, ...props }: React.ComponentProps<typeof Icon>) {
  const textClass = React.useContext(TextClassContext);
  return <Icon className={cn('size-4 shrink-0', textClass, className)} {...props} />;
}

export { Toggle, ToggleIcon, toggleVariants };
`
};
