name: Deploy Storybook Dev Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: react-native-usmds
  SERVICE: storybook-dev
  REGION: us-central1

jobs:
  deploy-to-cloudrun:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -f apps/storybook/Dockerfile -t gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA -t gcr.io/$PROJECT_ID/$SERVICE:latest .
          docker push gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA
          docker push gcr.io/$PROJECT_ID/$SERVICE:latest

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
          region: ${{ env.REGION }}
          project_id: ${{ env.PROJECT_ID }}
          flags: --port=8081 --cpu=2 --memory=2Gi --timeout=3600 --max-instances=10 --allow-unauthenticated
          env_vars: |
            EXPO_PUBLIC_STORYBOOK_ENABLED=true

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
